package com.example.provisioning.config;

import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Contact;
import io.swagger.v3.oas.models.info.Info;
import io.swagger.v3.oas.models.servers.Server;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import java.util.List;

/**
 * Top-level OpenAPI metadata. The per-endpoint / per-schema detail is
 * generated by springdoc from the controllers and DTOs; this bean only
 * supplies the document-level info and server list.
 *
 * <p>Live UI: {@code /swagger-ui.html} — raw spec: {@code /v3/api-docs}.
 */
@Configuration
public class OpenApiConfig {

    @Bean
    public OpenAPI provisioningOpenAPI() {
        return new OpenAPI()
            .info(new Info()
                .title("Organization Provisioning API")
                .version("1.0.0")
                .description("""
                    Organization Provisioning Workflow (Orchestrator pattern). \
                    A create request returns 202 Accepted immediately and drives a \
                    sequence of 12 external provisioning steps asynchronously, \
                    persisting per-step progress. A poll endpoint returns full \
                    workflow state.

                    Which steps run depends on the organization's orgType: it selects \
                    a profile in default_config.json that enables a set of config \
                    sections, and each conditional step runs only if its section is \
                    enabled — otherwise the step is recorded SKIPPED.""")
                .contact(new Contact().name("create-org-poc")))
            .servers(List.of(new Server().url("http://localhost:8080").description("Local")));
    }
}
