package com.example.provisioning.domain.model;

public enum StepName {
    CREATE_ORG_IN_FSP,
    SETUP_ORG_IN_FSP,
    ASSIGN_RECOMMENDATION_MODELS,
    SETUP_DEFAULT_BRANDING_PREFERENCES,
    SETUP_DEFAULT_PRM_PREFERENCES,
    SETUP_RFS_UI_PREFERENCES,
    SETUP_DEFAULT_VOCABULARIES_IN_CE,
    SETUP_DEFAULT_DATASOURCES,
    SETUP_DEFAULT_CITATION_STYLES,
    ENABLE_PRM_LICENSES,
    DISABLE_PRM_LICENSES,
    SETUP_FSP_BOOSTERS
}
